/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superpuissance_4;

import java.util.Random;
import java.util.Scanner;

/**
 *
 * @author nathan L
 */
public class FenetreDeJeu extends javax.swing.JFrame {

    Joueur[] ListeJoueur = new Joueur[2];
    Joueur joueurCourent;
    Grille newgrid = new Grille(); // on creer une nouvelle grille de reference newgrid

    /**
     * Creates new form FenetreDeJeu
     */
    public FenetreDeJeu() {
        initComponents();
        paneauinfojoueur.setVisible(false);
        paneau_info_partie.setVisible(false);

        for (int i = 6; i >= 0; i--) {
            for (int j = 0; j <= 5; j++) {
                CelluleGraphique cellGraph = new CelluleGraphique(newgrid.tab[i][j]);
                grillepanel.add(cellGraph);
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        grillepanel = new javax.swing.JPanel();
        paneau_creation_partie = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom_joueur1 = new javax.swing.JTextField();
        nom_joueur2 = new javax.swing.JTextField();
        btnstart = new javax.swing.JButton();
        paneau_info_partie = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbljactifnom = new javax.swing.JLabel();
        message = new javax.swing.JScrollPane();
        textemessage = new javax.swing.JTextArea();
        paneauinfojoueur = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblj1desint = new javax.swing.JLabel();
        lblj1nom = new javax.swing.JLabel();
        lblj1couleur = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblj2desint = new javax.swing.JLabel();
        lblj2couleur = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblj2nom1 = new javax.swing.JLabel();
        btncol0 = new javax.swing.JButton();
        btncol1 = new javax.swing.JButton();
        btncol2 = new javax.swing.JButton();
        btncol3 = new javax.swing.JButton();
        btncol4 = new javax.swing.JButton();
        btncol5 = new javax.swing.JButton();
        btncol6 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grillepanel.setBackground(new java.awt.Color(255, 255, 255));
        grillepanel.setLayout(new java.awt.GridLayout(6, 7));
        getContentPane().add(grillepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 672, 576));
        grillepanel.getAccessibleContext().setAccessibleName("");

        paneau_creation_partie.setBackground(new java.awt.Color(204, 255, 204));
        paneau_creation_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom Joueur 1 :");
        paneau_creation_partie.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 6, 90, 30));

        jLabel2.setText("Nom Joueur 2 :");
        paneau_creation_partie.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 36, 90, 30));
        paneau_creation_partie.add(nom_joueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 120, -1));

        nom_joueur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_joueur2ActionPerformed(evt);
            }
        });
        paneau_creation_partie.add(nom_joueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 120, -1));

        btnstart.setText("Demarer Partie");
        btnstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstartActionPerformed(evt);
            }
        });
        paneau_creation_partie.add(btnstart, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        getContentPane().add(paneau_creation_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 240, -1));

        paneau_info_partie.setBackground(new java.awt.Color(204, 255, 204));
        paneau_info_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel3.setText("Infos Jeux");
        paneau_info_partie.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel8.setText("joueur actif :");
        paneau_info_partie.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lbljactifnom.setText("nom joueur 2");
        paneau_info_partie.add(lbljactifnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        textemessage.setColumns(20);
        textemessage.setRows(5);
        message.setViewportView(textemessage);

        paneau_info_partie.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, -1));

        getContentPane().add(paneau_info_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 240, 190));

        paneauinfojoueur.setBackground(new java.awt.Color(204, 255, 204));
        paneauinfojoueur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("désintegrateur :");
        paneauinfojoueur.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 86, -1, 30));

        jLabel5.setText("Joueur 1 :");
        paneauinfojoueur.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel6.setText("Couleur :");
        paneauinfojoueur.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        lblj1desint.setText("nbdesintjoueur1");
        paneauinfojoueur.add(lblj1desint, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 86, -1, 30));

        lblj1nom.setText("nom joueur 1");
        paneauinfojoueur.add(lblj1nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        lblj1couleur.setText("couleur joueur");
        paneauinfojoueur.add(lblj1couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));
        paneauinfojoueur.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 210, 10));

        jLabel7.setText("désintegrateur :");
        paneauinfojoueur.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 30));

        jLabel9.setText("Couleur :");
        paneauinfojoueur.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        lblj2desint.setText("nbdesintjoueur");
        paneauinfojoueur.add(lblj2desint, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, 30));

        lblj2couleur.setText("couleur joueur 2");
        paneauinfojoueur.add(lblj2couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel10.setText("Infos Joueurs");
        paneauinfojoueur.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel11.setText("Joueur 2 :");
        paneauinfojoueur.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        lblj2nom1.setText("nom joueur 2");
        paneauinfojoueur.add(lblj2nom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        getContentPane().add(paneauinfojoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 240, 220));

        btncol0.setText("1");
        btncol0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncol0ActionPerformed(evt);
            }
        });
        getContentPane().add(btncol0, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        btncol1.setText("2");
        btncol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncol1ActionPerformed(evt);
            }
        });
        getContentPane().add(btncol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        btncol2.setText("3");
        btncol2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncol2ActionPerformed(evt);
            }
        });
        getContentPane().add(btncol2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        btncol3.setText("4");
        btncol3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncol3ActionPerformed(evt);
            }
        });
        getContentPane().add(btncol3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        btncol4.setText("5");
        btncol4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncol4ActionPerformed(evt);
            }
        });
        getContentPane().add(btncol4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        btncol5.setText("6");
        btncol5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncol5ActionPerformed(evt);
            }
        });
        getContentPane().add(btncol5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        btncol6.setText("7");
        btncol6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncol6ActionPerformed(evt);
            }
        });
        getContentPane().add(btncol6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        setBounds(0, 0, 1044, 702);
    }// </editor-fold>//GEN-END:initComponents

    private void nom_joueur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_joueur2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_joueur2ActionPerformed

    private void btncol0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncol0ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(0, grilleDeJeu);
        if (grilleDeJeu.derniereLigneDisponible(0) == 5) {
            btncol0.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_btncol0ActionPerformed

    private void btncol5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncol5ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(5, grilleDeJeu);
        if (grilleDeJeu.derniereLigneDisponible(5) == 5) {
            btncol5.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_btncol5ActionPerformed

    private void btncol6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncol6ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(6, grilleDeJeu);
        if (grilleDeJeu.derniereLigneDisponible(6) == 5) {
            btncol6.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_btncol6ActionPerformed

    private void btnstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstartActionPerformed
        paneauinfojoueur.setVisible(true);
        paneau_info_partie.setVisible(true);
        initialiserPartie();
        grillepanel.repaint();
        btnstart.setEnabled(false);

    }//GEN-LAST:event_btnstartActionPerformed

    private void btncol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncol1ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(1, grilleDeJeu);
        if (grilleDeJeu.derniereLigneDisponible(1) == 5) {
            btncol1.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_btncol1ActionPerformed

    private void btncol2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncol2ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(2, grilleDeJeu);
        if (grilleDeJeu.derniereLigneDisponible(2) == 5) {
            btncol2.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_btncol2ActionPerformed

    private void btncol3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncol3ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(3, grilleDeJeu);
        if (grilleDeJeu.derniereLigneDisponible(3) == 5) {
            btncol3.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_btncol3ActionPerformed

    private void btncol4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncol4ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(4, grilleDeJeu);
        if (grilleDeJeu.derniereLigneDisponible(4) == 5) {
            btncol4.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_btncol4ActionPerformed

    public void jouerDansColonne(int indice_colonne, Grille grilleDeJeu) {

        colonnechoisie = indice_colonne;
        newgrid = grilleDeJeu;
        // on stocke je jeton a mettre dans la variable jeto puis on suprime le referencement de ce heton dans la liste
        jeto = JoueurCourant.ListeJeton[JoueurCourant.positionDernierDuJetonNonNull()];
        JoueurCourant.ListeJeton[JoueurCourant.positionDernierDuJetonNonNull()] = null; // on lui enleve un jeton de sa liste (enfin je croi a voir quand on recupere les jeton

        // on stocke la derniere ligne disponible pour ne pas quel soit changer au cour de l'action ajouter jeton
        derniereLigneDisponible = newgrid.derniereLigneDisponible(colonnechoisie);

        // on va verifier si la cellules qu'il a choisi contient un trou noir
        if (!newgrid.tab[colonnechoisie][derniereLigneDisponible].presenceTrouNoir()) {
            System.out.println(derniereLigneDisponible);

            if (!newgrid.ajouterJetonDansColone(jeto, colonnechoisie)) {
                System.out.println("il n'y avait plus de place dans cette colone, soyez plus attentif la prochaine fois! vous passer votre tour");
            }

        } else {
            newgrid.tab[colonnechoisie][derniereLigneDisponible].suprimerTrouNoir();
        }

        // on va verifier si la cellules qu'il a choisi contient un desintegrateur
        if (newgrid.tab[colonnechoisie][derniereLigneDisponible].presenceDesintegrateur()) {
            newgrid.tab[colonnechoisie][derniereLigneDisponible].suprimerDesintegrateur();
            JoueurCourant.nombreDesintegrateurs++;
        }
        grillepanel.repaint();
        lblj1desint.setText(Listejoueurs[0].nombreDesintegrateurs+""); // met a jour les desintegrateur sur l'affichage
        lblj2desint.setText(Listejoueurs[1].nombreDesintegrateurs+"");
        
        boolean vict_j1 = newgrid.etreGagnantePourJoueur(ListeJoueur[0]);
        boolean vict_j2 = newgrid.etreGagnantePourJoueur(ListeJoueur[1]);
        
        if (vict_j1 && ! vict_j2) textemessage.setText("Victoire de : " + ListeJoueur[0].Nom );
        if (vict_j2 && ! vict_j1) textemessage.setText("Victoire de : " + ListeJoueur[1].Nom );
        
        if (vict_j1 && vict_j2){
            if (JoueurCourant == ListeJoueur[0]) textemessage.setText("Victoire de : " + ListeJoueur[1].Nom);
            else textemessage.setText("Victoire de : " + ListeJoueur[0].Nom + " ( faute de jeux )");
        }
    }

    public void joueurSuivant() {
        if (JoueurCourant == ListeJoueur[0]) {
            JoueurCourant = ListeJoueur[1];
        } else {
            JoueurCourant = ListeJoueur[0];
        }
        lbljactifnom.setText(JoueurCourant.Nom);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreDeJeu().setVisible(true);
            }
        });
    }

    int d; // on va l'utiliser dans le deroulement de la parte, permet de sauter une partie du code au premier tour dans le do while (l'inverseur de joueur pour le joueur actif)
    int derniereLigneDisponible; //on va l'utiliser dans une action ajouter un jeton pour stocker l'entier qui correspond à derniereLigneDisponible
    int colonnechoisie; //on va l'utiliser dans une action ajouter un jeton
    Jeton jeto;         //on va l'utiliser dans une action ajouter un jeton
    int colone; // on va l'utiliser pour recuperer des jeton dans case 2
    int ligne; // on va l'utiliser pour recuperer des jeton dans case 2

    Joueur Listejoueurs[] = new Joueur[2];
    Joueur JoueurCourant;
    Grille grilleDeJeu = new Grille();

    ;

    
    void attribuerCouleursAuxJoueurs() {
        Random r = new Random();
        boolean couleur;
        couleur = r.nextBoolean();
        if (couleur) {
            Listejoueurs[0].Couleur = "Rouge";
            Listejoueurs[1].Couleur = "Jaune";
        } else {
            Listejoueurs[0].Couleur = "Jaune";
            Listejoueurs[1].Couleur = "Rouge";
        }
    }

    Joueur ProchainJoueur(Joueur un_joueur) {
        if (Listejoueurs[0] == JoueurCourant) {
            return Listejoueurs[1];
        }
        return Listejoueurs[0];
    }

    void initialiserPartie() {
        //Mise en place de la grille
        grilleDeJeu.viderGrille();

        //Création des joueurs
        String nomjoueur1 = nom_joueur1.getText();
        String nomjoueur2 = nom_joueur2.getText();
        Joueur J1 = new Joueur(nomjoueur1);
        Joueur J2 = new Joueur(nomjoueur2);
        Listejoueurs[0] = J1;
        Listejoueurs[1] = J2;

        attribuerCouleursAuxJoueurs();

        System.out.println(J1.Nom + " est de couleur " + J1.Couleur);
        System.out.println(J2.Nom + " est de couleur " + J2.Couleur);

        lblj1nom.setText(nomjoueur1);
        lblj2nom1.setText(nomjoueur2);
        lblj1couleur.setText(J1.Couleur);
        lblj2couleur.setText(J2.Couleur);
        lblj1desint.setText(J1.nombreDesintegrateurs + "");
        lblj2desint.setText(J2.nombreDesintegrateurs + "");

        // On donne des jetons aux joueurs
        for (int i = 0; i < 21; i++) {

            Jeton J = new Jeton(Listejoueurs[0].Couleur);

            J1.ajouterJeton(J);

            J2.ajouterJeton(new Jeton(J2.Couleur));
        }

        // Determine qui est le premier joueur
        Random r = new Random();
        boolean le_premier = r.nextBoolean();
        if (le_premier) {
            JoueurCourant = Listejoueurs[0];
        } else {
            JoueurCourant = Listejoueurs[1];
        }

        lbljactifnom.setText(JoueurCourant.Nom);

        // Génération des 5 trous noirs et de 2 désintégrateurs sur les trou noirs
        int compteur = 0;
        for (int i = 0; i < 5; i++) {
            int ligne_trou_noir = r.nextInt(6);
            int colonne_trou_noir = r.nextInt(7);
            if (compteur < 2) {
                if (!grilleDeJeu.tab[colonne_trou_noir][ligne_trou_noir].placerDesintegrateur()) {
                    compteur--;
                }
                compteur = compteur + 1;
            }
            if (!grilleDeJeu.tab[colonne_trou_noir][ligne_trou_noir].placerTrouNoir()) {
                i--;
            }
        }

        // On place les trois derniers désintégrateurs
        for (int i = 0; i < 3; i++) {
            int ligne_désin = r.nextInt(6);
            int colonne_désin = r.nextInt(7);
            if (!grilleDeJeu.tab[colonne_désin][ligne_désin].placerDesintegrateur() || grilleDeJeu.tab[colonne_désin][ligne_désin].presenceTrouNoir()) {
                i--;
            }
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncol0;
    private javax.swing.JButton btncol1;
    private javax.swing.JButton btncol2;
    private javax.swing.JButton btncol3;
    private javax.swing.JButton btncol4;
    private javax.swing.JButton btncol5;
    private javax.swing.JButton btncol6;
    private javax.swing.JButton btnstart;
    private javax.swing.JPanel grillepanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblj1couleur;
    private javax.swing.JLabel lblj1desint;
    private javax.swing.JLabel lblj1nom;
    private javax.swing.JLabel lblj2couleur;
    private javax.swing.JLabel lblj2desint;
    private javax.swing.JLabel lblj2nom1;
    private javax.swing.JLabel lbljactifnom;
    private javax.swing.JScrollPane message;
    private javax.swing.JTextField nom_joueur1;
    private javax.swing.JTextField nom_joueur2;
    private javax.swing.JPanel paneau_creation_partie;
    private javax.swing.JPanel paneau_info_partie;
    private javax.swing.JPanel paneauinfojoueur;
    private javax.swing.JTextArea textemessage;
    // End of variables declaration//GEN-END:variables
}
